# Generated by Django 2.0.7 on 2018-09-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180912_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
    ]
