# Generated by Django 2.0.7 on 2018-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=200, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(max_length=150, null=True, verbose_name='handle'),
        ),
    ]
