# Generated by Django 2.0.7 on 2018-09-13 12:39

from django.db import migrations, models
import project.user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180912_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_code',
            field=models.CharField(default=project.user_profile.models.code_generator, max_length=15, verbose_name='registration_code'),
        ),
    ]
