# Generated by Django 2.0.7 on 2018-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='handle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
    ]
