# Generated by Django 2.0.7 on 2018-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180913_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='joined_date'),
        ),
    ]
