# Generated by Django 2.0.7 on 2018-09-07 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('category', models.CharField(choices=[('consulting', 'Consulting'), ('banking', 'Banking'), ('catering', 'Catering'), ('chemical', 'Chemical'), ('construction', 'Construction'), ('electronics', 'Electronics'), ('finance', 'Finance'), ('graphic art ', 'Graphic Art '), ('information', 'Information'), ('manufacturing', 'Manufacturing'), ('care', 'Care'), ('marketing', 'Marketing'), ('social', 'Social'), ('logistic', 'Logistics'), ('sales', 'Sales'), ('sport', 'Sport'), ('transport', 'Transport')], max_length=100, verbose_name='category')),
                ('image', models.ImageField(blank=True, null=True, upload_to='knowledge/', verbose_name='picture of your knowledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
